-- Apply before deploying the Host: production uses PG_ENSURE_SCHEMA=false.
-- Child Sessions reuse existing Session, pending-input, event-log and lease
-- tables; coordination records carry no credentials or runtime capabilities.
BEGIN;
ALTER TABLE oma.sessions ADD COLUMN IF NOT EXISTS delegation JSONB;
ALTER TABLE oma.pending_events ADD COLUMN IF NOT EXISTS interrupt_requested_at TIMESTAMPTZ;
ALTER TABLE oma.pending_events ADD COLUMN IF NOT EXISTS interrupt_generation BIGINT;

CREATE TABLE IF NOT EXISTS oma.delegation_lock (id TEXT PRIMARY KEY);
INSERT INTO oma.delegation_lock (id) VALUES ('coordination') ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS oma.delegation_executions (id TEXT PRIMARY KEY, record JSONB NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS delegation_caller_identity_idx ON oma.delegation_executions
  ((record->>'tenantId'), (record->>'callerSessionId'), (record->>'callerTurnId'), (record->>'callerToolUseId'));
CREATE UNIQUE INDEX IF NOT EXISTS delegation_pending_identity_idx ON oma.delegation_executions ((record->>'pendingEventId'));
CREATE INDEX IF NOT EXISTS delegation_child_idx ON oma.delegation_executions ((record->>'tenantId'), (record->>'childId'));
CREATE INDEX IF NOT EXISTS delegation_caller_idx ON oma.delegation_executions ((record->>'tenantId'), (record->>'callerSessionId'));
CREATE TABLE IF NOT EXISTS oma.delegation_waits (id TEXT PRIMARY KEY, record JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS oma.delegation_commands (id TEXT PRIMARY KEY, record JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS oma.delegation_resource_uses (id TEXT PRIMARY KEY, record JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS oma.delegation_environments (id TEXT PRIMARY KEY, sandbox_id TEXT);

-- Explicitly reset inherited default ACLs: no CREATE, TRUNCATE, REFERENCES or
-- TRIGGER permission is needed. SELECT FOR UPDATE requires UPDATE privilege on
-- the coordination row. IDs are generated by the Host, so no new sequences.
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'oma_app') THEN
    REVOKE ALL PRIVILEGES ON TABLE oma.delegation_lock, oma.delegation_executions,
      oma.delegation_waits, oma.delegation_commands, oma.delegation_resource_uses,
      oma.delegation_environments FROM oma_app;
    GRANT USAGE ON SCHEMA oma TO oma_app;
    GRANT SELECT, UPDATE ON TABLE oma.delegation_lock TO oma_app;
    GRANT SELECT, INSERT, UPDATE ON TABLE oma.delegation_executions,
      oma.delegation_waits, oma.delegation_commands, oma.delegation_environments TO oma_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE oma.delegation_resource_uses TO oma_app;
  END IF;
END;
$migration$;
COMMIT;
